### PR TITLE
WIP : Fix/rnchanges/0.2

### PR DESCRIPTION
**Pull request by abdulmuneer22**

### CODE REVIEW

**Comment by Parsh** [comment]
Shutting down, stale WIP PR. Please re-open the PR when it's ready to be merged.

**Review by Parsh — CHANGES_REQUESTED** [review]
There are quite a few issues with this PR. We should not move ahead with the merge unless we rectify them.

**Review by AliMeer — CHANGES_REQUESTED** [review]
Files marked 'viewed' need to be retained from dev branch.

The following need to be reviewed and assessed:

src/pages/ManageBackup/HealthCheckSecurityQuestion.tsx
src/storage/database-manager.ts
src/storage/secure-store.ts
src/store/sagas/sss.ts

**Review by Parsh — APPROVED** [review]
LGTM

**Review by AliMeer — APPROVED** [review]

**Pull request merged**
