### PR TITLE
Additional readability improvements.

### PR DESCRIPTION
**Pull request by sz3k**
Also fixed a typo after catching it in the test account "Know More" sheet.

### CODE REVIEW

**Comment by AliMeer** [comment]
@sz3k Thanks a lot for the suggestions 😊

We have some feedback for all the suggestions, attached document has all the text incorporating your suggestions as well as some changes.

Are you able incorporate these in your PR?

[Know More text 16.2.21.docx](https://github.com/bithyve/hexa/files/5990246/Know.More.text.16.2.21.docx)

**Comment by sz3k** [comment]
> @sz3k Thanks a lot for the suggestions 😊
> 
> We have some feedback for all the suggestions, attached document has all the text incorporating your suggestions as well as some changes.
> 
> Are you able incorporate these in your PR?
> 
> [Know More text 16.2.21.docx](https://github.com/bithyve/hexa/files/5990246/Know.More.text.16.2.21.docx)

I have updated the Manage Backup screen with the lines provided.

**Comment by AliMeer** [comment]
> 
> I have updated the Manage Backup screen with the lines provided.
> 

There are more pages :) fo Keeper Device, F&F Request, Personal Copy, Test Account, Checking Account, Saving Account, Send, Receive, Donation Account and the rest

**Comment by sz3k** [comment]
AH! Somehow I totally missed that. Will start work on this now.

**Review by AliMeer — APPROVED** [review]
Awesome changes! Thanks a bunch @sz3k

**Comment by sz3k** [comment]
No problem! Happy to help

**Pull request merged**
