### PR TITLE
Feature/app version header

### PR DESCRIPTION
**Pull request by abdulmuneer22**

### CODE REVIEW

**Comment by abdulmuneer22** [comment]
> bittr is a integration that we will not be using in the future.

Okay, let me move all these instances to a separate folder for APIs

**Comment by AliMeer** [comment]
> > bittr is a integration that we will not be using in the future.
> 
> > Okay, let me move all these instances to a separate folder for APIs
> 
> Yes, `src/services/` was meant to be the common folder. Where do you plan to move this?

We wont be using any services from bittr.ts but we will be using services in src/services/fbtc.ts

**Comment by Parsh** [comment]
Mostly everything LGTM. The only suggestion I have is if we can move BH_AXIOS and SIGNING_SERVER instance creation in bitcoin/Config.ts as it would be nice to have all the core bitcoin code and its dependencies into that single folder such that it remains ejectable.

Also, both of those instances aren't used anywhere else except there.

**Comment by AliMeer** [comment]
> Mostly everything LGTM. The only suggestion I have is if we can move BH_AXIOS and SIGNING_SERVER instance creation in bitcoin/Config.ts as it would be nice to have all the core bitcoin code and its dependencies into that single folder such that it remains ejectable.
> 
> Also, both of those instances aren't used anywhere else except there.

@abdulmuneer22 are you planning to do this change now are in a later PR?

**Comment by abdulmuneer22** [comment]
> > Mostly everything LGTM. The only suggestion I have is if we can move BH_AXIOS and SIGNING_SERVER instance creation in bitcoin/Config.ts as it would be nice to have all the core bitcoin code and its dependencies into that single folder such that it remains ejectable.
> > Also, both of those instances aren't used anywhere else except there.
> 
> @abdulmuneer22 are you planning to do this change now are in a later PR?

an API service would make more sense in services folder than config, I guess we can take this change for later

**Pull request merged**
